### ISSUE TITLE
API creation

### ISSUE THREAD

**Issue by fedepacher** [fedepacher/rag#2]
# Description

Create an API in which a user must register to access the system. After registration, the user can interact with the RAG system. 

## Tasks

- [x] Create an endpoint to register a new user.
- [x] Store the user in a relational database.
- [x] Create an endpoint to log in and return a token.
- [x] Create an endpoint to ask a question (prompt).
