### ISSUE TITLE
Data collection database

### ISSUE THREAD

**Issue by fedepacher** [fedepacher/rag#4]
# Description

Collect questions and answers in a NoSQL database for future training model. This will also be the connection between services.

## Tasks

- [x] Store Q&A in a MongoDB.
- [x] Connect DB with the API.
- [x] Connect DB with RAG system.

## Note 

The Database will have the following structure:
```
{
  id: Unique ID for each prompt.
  input: User prompt.
  date: Timestamp.
  output: RAG system output
  context: Document where the RAG will find the answer.
  email: email of the user who wrote the input.
}
```
