### ISSUE TITLE
Connect RAG with DB 

### ISSUE THREAD

**Issue by fedepacher** [fedepacher/rag#8]
# Description

Could you get the prompt and the document to store the answer from a NoSQL database (MongoDB). The API writes the prompt input in MongoDB, the RAG process must read the database and find the questions without answers ordered by the timestamp. The oldest timestamp will be the first in the line to be answered.

## Tasks 

- [ ] Connect the DB with the RAG system
- [ ] Interact with the DB
- [ ] Store the output in the database
